language: ruby
rvm:
  - 2.5.3
before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install -g yarn
install:
  - bundle check || bundle install
  - bundle update
  - yarn install --modules-folder ./_assets/yarn
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: dev